version: '3'

services:
# on donne le nom que l'on souhaite à la base de données
  db:
    image: mysql
    container_name: db_symfony
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_symfony
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - dev
  
  maildev:
    image: maildev/maildev
    container_name: maildev_symfony
    ports:
      - '8081:80'
    restart: always
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    networks:
      - dev
  
  www: 
    build: php
    container_name: www_symfony
    ports: 
      - 8741:80
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - dev

networks:
  dev:

volumes:
  db-data:
